# Generated by Django 4.2.7 on 2023-12-02 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cedente_contato_alter_sacado_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
