# Generated by Django 4.2.7 on 2023-12-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_titulo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titulo',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
