# Generated by Django 4.2.7 on 2023-12-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_link_templatewhatsapp_alter_arquivo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatewhatsapp',
            name='link',
        ),
    ]
