# Generated by Django 4.2.7 on 2023-12-29 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_remove_titulo_observacao_observacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observacao",
            old_name="observacao",
            new_name="descricao",
        ),
    ]
