# Generated by Django 4.2.7 on 2024-01-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_rename_observacao_observacao_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="titulo",
            name="contato_secundario",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
