# Generated by Django 4.2.7 on 2024-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_titulo_contato_secundario"),
    ]

    operations = [
        migrations.AddField(
            model_name="titulo",
            name="marcado",
            field=models.BooleanField(default=False),
        ),
    ]
