# Generated by Django 4.2.7 on 2024-02-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_titulo_encargo"),
    ]

    operations = [
        migrations.AddField(
            model_name="titulo",
            name="valor_face",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
