# Generated by Django 4.2.7 on 2024-02-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_operador_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="titulo",
            name="operador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.operador",
            ),
        ),
        migrations.AddField(
            model_name="titulo",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.supervisor",
            ),
        ),
    ]
